### ISSUE TITLE
Will it be possible to run this port on Google Cardboard?

### ISSUE THREAD

**Issue by jpmckinney** [BeAnotherLab/The-Machine-to-be-Another-Unity#1]

**Comment by ReallyRad** [comment]
Hey James, that's indeed our intention. The tricky part will be to manage the video streaming with webRTC. Some of our collaborators are investigating the possibility at the moment.

**Comment by jpmckinney** [comment]
Great! I ordered a Google Cardboard and installed Unity on OS X, so if/when the code is at a stage where I can run it, I can do some testing.
