### ISSUE TITLE
Which Arduino to buy?

### ISSUE THREAD

**Issue by jpmckinney** [BeAnotherLab/The-Machine-to-be-Another-Unity#2]
I have all the components except an Arduino. Which do you recommend?

https://store.arduino.cc/

**Comment by ReallyRad** [comment]
Hey James, 
Are the components you bought the ones listed in the "building the vest" section on [the docs] (https://github.com/BeAnotherLab/The-Machine-to-be-Another) ?

We have been working on a cheaper vest setup without any 3D-printed, using gopro harnesses .
Also we recommend using better quality cameras like [this one](http://www.amazon.com/180degree-Fisheye-1080p-Angle-Camera/dp/B00LQ854AG)
We will update the docs soon.

Why don't you drop us an email at beanotherlab@gmail.com to tell us a bit about your intentions :)

**Comment by jpmckinney** [comment]
The readme for this project mentions an Arduino - maybe it's not needed for the body swap experiment that I'm interested in. I don't intend to build a vest. I'll send an email as well :)

**Comment by ReallyRad** [comment]
yes, the body swap experiment only requires the equipment in the diagram. No arduino needed

**Comment by jpmckinney** [comment]
K, thanks!
